language: csharp

mono:
  - latest
dotnet:
  - latest

sudo: false  # use the new container-based Travis infrastructure 

before_install:
  - chmod +x build.sh
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
  - mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/

before_script: 
  - git lfs pull

script: 
  - ./build.sh All
